version: '3.8'

services:
  backend:
    build: ./backend
    container_name: contacts-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    networks:
      - contacts-network
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: contacts-frontend
    ports:
      - "5173:80"
    networks:
      - contacts-network
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: contacts-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - contacts-network

networks:
  contacts-network:

volumes:
  mongo_data:
